# Default values for marschart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: default

marsimage:
  repository: nocsysmars/mars
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"
  defaultAPP: "drivers,com.nocsys.drivers.nocsys.gnmi,com.nocsys.drivers.nocsys.rest,com.nocsys.drivers.nocsys.snmp,proxyarp,restsb,snmp,org.onosproject.netconf,org.onosproject.drivers.netconf,org.onosproject.drivers.h3c.netconf,linkdiscovery,com.nocsys.provider.switchpolling,com.nocsys.eventclient,com.nocsys.useraccount,com.nocsys.defaultcfg,com.nocsys.alert,com.nocsys.analyzer,com.nocsys.utility,com.nocsys.healthycheck,com.nocsys.dhcprelay,com.nocsys.dhcpserver,com.nocsys.dhcpv6server,com.nocsys.logicalport,com.nocsys.endpoint,com.nocsys.monitor,com.nocsys.ntpserver,com.nocsys.qos,com.nocsys.sflow,com.nocsys.storm-control,com.nocsys.switchmgmt,com.nocsys.egp,com.nocsys.tenant,com.nocsys.tenantlogicalrouter,com.nocsys.topology,com.nocsys.acl,com.nocsys.websocket,com.nocsys.webssh"
  defaultTopology: clos
  
nginximage:
  repository: nocsysmars/nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.14.0"
  
esimage:
  repository: nocsysmars/elasticsearch
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.9.0-oss"

logstashimage:
  repository: nocsysmars/logstash
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.5.2-oss"
  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 443

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  mars:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #  limits:
  #    cpu: 500m
  #   memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
  es:
    requests:
      cpu: 500m
      memory: 1000Mi
  logstash:
    requests:
      cpu: 500m
      memory: 1000Mi
nginx:
    requests:
      cpu: 500m
      memory: 1000Mi
      
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
