apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "marschart.fullname" . }}
  labels:
    {{- include "marschart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "marschart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "marschart.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-es
          persistentVolumeClaim:
            claimName: es-data
        - name: volume-mars
          persistentVolumeClaim:
            claimName: mars-download
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "marschart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: container-mars
          image: {{ .Values.marsimage.repository }}:{{ .Values.marsimage.tag }}
          ports:
            - name: http-0
              containerPort: 8101
              protocol: TCP
            - name: http-1
              containerPort: 8181
              protocol: TCP
          env:
            - name: ONOS_TOPOLOGY
              value: {{ .Values.marsimage.defaultTopology }}
            - name: ONOS_APPS
              value: {{ .Values.marsimage.defaultAPP }}
                
            - name: ONOS_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ES_HOSTS
              value: '127.0.0.1:9200'
          resources:
            {{- toYaml .Values.resources.mars | nindent 12 }}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-mars
              mountPath: /root/onos/download
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: container-nginx
          image: {{ .Values.nginximage.repository }}:{{ .Values.nginximage.tag }}
          ports:
            - name: tcp-443
              containerPort: 443
              protocol: TCP
            - name: tcp-69
              containerPort: 69
              protocol: TCP
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: container-logstash
          image: {{ .Values.logstashimage.repository }}:{{ .Values.logstashimage.tag }}
          ports:
            - name: tcp-25826
              containerPort: 25826
              protocol: TCP
            - name: tcp-5044
              containerPort: 5044
              protocol: TCP
            - name: tcp-514
              containerPort: 514
              protocol: TCP
            - name: tcp-5514
              containerPort: 5514
              protocol: TCP
            - name: tcp-6343
              containerPort: 6343
              protocol: TCP
            - name: tcp-6614
              containerPort: 6614
              protocol: TCP
            - name: tcp-9600
              containerPort: 9600
              protocol: TCP
          env:
            - name: ES_HOSTS
              value: 127.0.0.1
          resources:
            {{- toYaml .Values.resources.logstash | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: container-es
          image: {{ .Values.esimage.repository }}:{{ .Values.esimage.tag }}
          ports:
            - name: tcp-9200
              containerPort: 9200
              protocol: TCP
            - name: tcp-9300
              containerPort: 9300
              protocol: TCP
          env:
            - name: cluster.name
              value: marsesdb
            - name: ES_JAVA_OPTS
              value: ' -Xms256m -Xmx256m'
            - name: node.master
              value: 'true'
            - name: discovery.zen.minimum_master_nodes
              value: '1'
            - name: cluster.initial_master_nodes
              value: marsdb-node
            - name: node.name
              value: marsdb-node
            - name: network.host
              value: 127.0.0.1
            - name: network.publish_host
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            {{- toYaml .Values.resources.es | nindent 12 }}
          volumeMounts:
            - name: volume-es
              mountPath: /usr/share/elasticsearch/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
